# Generated by Django 3.2.6 on 2021-08-27 13:39

from django.db import migrations, models
import movies.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FilmWork',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('title', models.TextField()),
                ('description', models.TextField(null=True)),
                ('creation_date', models.DateField(null=True)),
                ('file_path', models.FilePathField(null=True)),
                ('rating', models.DecimalField(decimal_places=1, max_digits=2, null=True)),
                ('type', models.CharField(max_length=30)),
            ],
            options={
                'verbose_name': 'filmwork',
                'verbose_name_plural': 'filmworks',
                'db_table': 'film_work',
                'managed': False,
            },
            bases=(movies.models.TimeStampedMixin, models.Model),
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('description', models.TextField(null=True)),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'genre',
                'verbose_name_plural': 'genres',
                'db_table': 'genre',
                'managed': False,
            },
            bases=(movies.models.TimeStampedMixin, models.Model),
        ),
        migrations.CreateModel(
            name='GenreFilmWork',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'film_work_genre',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('full_name', models.CharField(max_length=30)),
                ('birth_date', models.TextField(null=True)),
            ],
            options={
                'db_table': 'person',
                'managed': False,
            },
            bases=(movies.models.TimeStampedMixin, models.Model),
        ),
        migrations.CreateModel(
            name='PersonFilmWork',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[('director', 'директор'), ('writer', 'сценарист'), ('actor', 'актер')], max_length=20, verbose_name='роль')),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'person_film_work',
                'managed': False,
            },
        ),
    ]
