version: '3.8'

volumes:
  postgres_data:
  static_volume:
  media_volume:

services:
  ma_postgres:
    image: postgres:13.4
    container_name: ma_postgres
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data/
      - ./schema_design/db_schema.sql:/docker-entrypoint-initdb.d/db_schema.sql
    env_file:
      - sqlite_to_postgres/.env
    expose:
      - 5432
    ports:
      - "5432:5432"
    # Не понял для чего прятать порты. Для защиты, думаю вряд ли. Так как попробовал сделать так
    # docker container inspect ma_postgres -- тут узнал ip "IPAddress": "172.28.0.2".
    # Все равно подключился. А без портов просто усложняет саму работу, как по мне для защиты нужно в
    # postgres установить норм пароли, возможность заходить только с определённых ip.
    # А если злоумышленник пробрался на сервер, где крутится докер - +1 команда к его работе и он все равно
    # сделает что ему нужно

  ma_web:
    build: .
    restart: always
    container_name: ma_web
    depends_on:
      - ma_postgres
    env_file:
      - movies_admin/.env
    volumes:
      - static_volume:/sites/static/

  ma_nginx:
    image: nginx:1.19.2
    container_name: ma_nginx
    depends_on:
      - ma_web
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/sites-enabled/:/etc/nginx/sites-enabled/
      - static_volume:/sites/static/
    ports:
      - "80:80"