version: '3.8'

volumes:
  postgres_data:
  static_volume:
  media_volume:

services:
  ma_postgres:
    image: postgres:latest
    container_name: ma_postgres
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data/
      - ./schema_design/db_schema.sql:/docker-entrypoint-initdb.d/db_schema.sql
    env_file:
      - sqlite_to_postgres/.env
    expose:
      - 5432
    ports:
      - "5432:5432"

  ma_web:
    build: .
    restart: always
    container_name: ma_web
    command: bash -c "python manage.py migrate && python manage.py collectstatic --noinput && gunicorn config.wsgi:application --preload --bind 0.0.0.0:8000"
    depends_on:
      - ma_postgres
    env_file:
      - .env
    volumes:
      - static_volume:/sites/movies_admin/static/
    expose:
      - 8000
    ports:
      - "8000:8000"

  ma_nginx:
    image: nginx:1.19.2
    container_name: ma_nginx
    depends_on:
      - ma_web
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/sites-enabled/:/etc/nginx/etc/nginx/sites-enabled/movies_admin.conf
      - static_volume:/sites/movies_admin/static/
